#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Sat Apr 24 17:18:19 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((471, 370))
        self.SetTitle("frame")

        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        sizer_1.Add(self.panel_1, 8, wx.EXPAND, 0)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        self.slider_1 = wx.Slider(self, wx.ID_ANY, 100, 0, 255)
        sizer_2.Add(self.slider_1, 0, wx.EXPAND, 0)

        self.slider_2 = wx.Slider(self, wx.ID_ANY, 100, 0, 255)
        sizer_2.Add(self.slider_2, 0, wx.EXPAND, 0)

        self.slider_3 = wx.Slider(self, wx.ID_ANY, 100, 0, 255)
        sizer_2.Add(self.slider_3, 0, wx.EXPAND, 0)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self, wx.ID_ANY, "R")
        sizer_3.Add(label_1, 0, wx.TOP, 4)

        label_2 = wx.StaticText(self, wx.ID_ANY, "G")
        sizer_3.Add(label_2, 0, wx.TOP, 4)

        label_3 = wx.StaticText(self, wx.ID_ANY, "B")
        sizer_3.Add(label_3, 0, wx.TOP, 5)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)

        self.text_ctrl_3 = wx.TextCtrl(self, wx.ID_ANY, "")
        sizer_4.Add(self.text_ctrl_3, 0, 0, 0)

        self.text_ctrl_4 = wx.TextCtrl(self, wx.ID_ANY, "")
        sizer_4.Add(self.text_ctrl_4, 0, 0, 0)

        self.text_ctrl_5 = wx.TextCtrl(self, wx.ID_ANY, "")
        sizer_4.Add(self.text_ctrl_5, 0, 0, 0)

        self.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_COMMAND_SCROLL, self.change_color, self.slider_1)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.change_color, self.slider_2)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.change_color, self.slider_3)
        # end wxGlade

    def change_color(self, event):  # wxGlade: MyFrame.<event_handler>
        r = self.slider_1.GetValue()
        g = self.slider_2.GetValue()
        b = self.slider_3.GetValue()
        self.text_ctrl_3.Value=str(r)
        self.text_ctrl_4.Value = str(b)
        self.text_ctrl_5.Value = str(g)

        self.panel_1.SetBackgroundColour((r, g, b))
        self.panel_1.Refresh(True)


# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
