#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Sat May 22 20:37:30 2021
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((614, 511))

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.static_line_1 = wx.StaticLine(self, wx.ID_ANY)
        self.panel_2 = wx.Panel(self, wx.ID_ANY)

        self.data_browser = wx.Button(self.panel_1, wx.ID_ANY, "D")
        self.refresh = wx.Button(self.panel_1, wx.ID_ANY, u"数据集刷新")
        self.reach_selector = wx.Choice(self.panel_1, wx.ID_ANY, choices=[])
        self.mtime_selector = wx.Choice(self.panel_1, wx.ID_ANY, choices=[])
        self.pdf = wx.Button(self.panel_1, wx.ID_ANY, "PDF")
        self.MtimeLevel = wx.ToggleButton(self.panel_1, wx.ID_ANY, u"测时水位")
        self.marker = wx.ToggleButton(self.panel_1, wx.ID_ANY, u"显示测点")
        self.hasgrid = wx.ToggleButton(self.panel_1, wx.ID_ANY, u"网格")
        self.haslegend = wx.ToggleButton(self.panel_1, wx.ID_ANY, u"图例")

        self.__set_properties()
        self.__do_layout()

    def __set_properties(self):
        self.SetTitle(("小浪底水库淤积测验处理程序"))


    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_pane_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_pane_1_command = wx.BoxSizer(wx.HORIZONTAL)

        sizer_pane_1_command.Add(self.data_browser, 0, wx.ALIGN_CENTER, 0)
        sizer_pane_1_command.Add((3, 20), 0, wx.ALIGN_CENTER, 0)
        sizer_pane_1_command.Add(self.refresh, 0, wx.ALIGN_CENTER, 0)
        sizer_pane_1_command.Add((20, 20), 0, wx.ALIGN_CENTER, 0)
        sizer_pane_1_command.Add(self.reach_selector, 0, wx.ALIGN_CENTER, 0)
        sizer_pane_1_command.Add((20, 20), 0, wx.ALIGN_CENTER, 0)
        sizer_pane_1_command.Add(self.mtime_selector, 0, wx.ALIGN_CENTER, 0)
        sizer_pane_1_command.Add((20, 20), 0, wx.ALIGN_CENTER, 0)
        sizer_pane_1_command.Add(self.pdf, 0, wx.ALIGN_CENTER, 0)
        sizer_pane_1_command.Add((20, 20), 0, wx.ALIGN_CENTER, 0)
        sizer_pane_1_command.Add(self.MtimeLevel, 0, wx.ALIGN_CENTER, 0)
        sizer_pane_1_command.Add((20, 20), 0, wx.ALIGN_CENTER, 0)
        sizer_pane_1_command.Add(self.marker, 0, wx.ALIGN_CENTER, 0)
        sizer_pane_1_command.Add((20, 20), 0, wx.ALIGN_CENTER, 0)
        sizer_pane_1_command.Add(self.hasgrid, 0, wx.ALIGN_CENTER, 0)
        sizer_pane_1_command.Add((20, 20), 0, wx.ALIGN_CENTER, 0)
        sizer_pane_1_command.Add(self.haslegend, 0, wx.ALIGN_CENTER, 0)
        sizer_pane_1_command.Add((20, 20), 0, wx.ALIGN_CENTER, 0)

        sizer_pane_1.Add(sizer_pane_1_command, 1, 0, 0)

        sizer_1.Add(self.panel_1, 1 ,wx.ALL | wx.EXPAND, 8)
        sizer_1.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizer_1.Add(self.panel_2, 3, wx.ALL | wx.EXPAND, 8)



        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class MyFrame


class MyApp(wx.App):
    def OnInit(self):
        self.frame_1 = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame_1)
        self.frame_1.Show()
        return True

# end of class MyApp


if __name__ == "__main__":
    gettext.install("app")  # replace with the appropriate catalog name
    app = MyApp(0)
    app.MainLoop()
